# Configurations
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        none

excerpt_separator: "<!--more-->"

# Setup
title:            'Jekyll Metro'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              'http://compile-me.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/


# Author Details
author:         'Abdel Raoof Olakara'

#Social Media links
linkedin:       'https://www.linkedin.com/pub/%E6%B6%9B-%E4%BD%95/bb/868/732'
twitter:        'https://twitter.com/olakara'
facebook:       'https://www.facebook.com/olakara'
gplus:          'https://plus.google.com/112661429129878562674/'

# Google Analytics
gahandler: '' # 'UA-52149651-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: sighingnow@gmail.com
  facebook:
  flickr:
  github: sighingnow
  instagram:
  linkedin: pub/%E6%B6%9B-%E4%BD%95/bb/868/732
  pinterest:
  rss: /feed.xml # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: 112661429129878562674
  twitter: 
  stackoverflow: #users/4388898/peter-zhu # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.8
